/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 basic_guild_pass.glb --transform --types
Files: basic_guild_pass.glb [10.27MB] > /home/senkora/projects/guild.xyz/public/models/basic_guild_pass-transformed.glb [551.1KB] (95%)
*/

import { useGLTF } from "@react-three/drei"
import * as THREE from "three"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    Curve: THREE.Mesh
    Curve001: THREE.Mesh
    Curve003: THREE.Mesh
  }
  materials: {
    SVGMat: THREE.MeshStandardMaterial
    "Material.001": THREE.MeshStandardMaterial
    "Material.002": THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/basic_guild_pass-transformed.glb"
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials.SVGMat}
        scale={6.649}
      />
      <mesh
        geometry={nodes.Curve001.geometry}
        material={materials["Material.001"]}
        position={[-1.598, 0.015, 0.781]}
        scale={6.86}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={materials["Material.002"]}
        position={[-0.597, 0.018, 0.315]}
        scale={6.104}
      />
    </group>
  )
}

useGLTF.preload("/models/basic_guild_pass-transformed.glb")
